### ISSUE TITLE
Test errors

### ISSUE THREAD

**Issue by Arfrever** [testing-cabal/traceback2#1]
I use linecache2-1.0.0, unittest2 1.0.1.
Output of test suite for traceback2 trunk:

```
$ python2.7 -m unittest2 discover
.EEEEE.....E....................ss..s..........
======================================================================
ERROR: test_cause (traceback2.tests.test_traceback.PyExcReportingTests)
traceback2.tests.test_traceback.PyExcReportingTests.test_cause
----------------------------------------------------------------------
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
SkipTest: Only applies to 3.2+


======================================================================
ERROR: test_cause_and_context (traceback2.tests.test_traceback.PyExcReportingTests)
traceback2.tests.test_traceback.PyExcReportingTests.test_cause_and_context
----------------------------------------------------------------------
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
SkipTest: Only applies to 3.2+


======================================================================
ERROR: test_cause_recursive (traceback2.tests.test_traceback.PyExcReportingTests)
traceback2.tests.test_traceback.PyExcReportingTests.test_cause_recursive
----------------------------------------------------------------------
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
SkipTest: Only applies to 3.2+


======================================================================
ERROR: test_context (traceback2.tests.test_traceback.PyExcReportingTests)
traceback2.tests.test_traceback.PyExcReportingTests.test_context
----------------------------------------------------------------------
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
SkipTest: Only applies to 3.2+


======================================================================
ERROR: test_context_suppression (traceback2.tests.test_traceback.PyExcReportingTests)
traceback2.tests.test_traceback.PyExcReportingTests.test_context_suppression
----------------------------------------------------------------------
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
SkipTest: Only applies to 3.3+


======================================================================
ERROR: test_encoded_file (traceback2.tests.test_traceback.SyntaxTracebackCases)
traceback2.tests.test_traceback.SyntaxTracebackCases.test_encoded_file
----------------------------------------------------------------------
Traceback (most recent call last):
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "traceback2/tests/test_traceback.py", line 225, in test_encoded_file
    do_test("", "foo", "ascii", 3, output_encoding)
  File "traceback2/tests/test_traceback.py", line 217, in do_test
    stdout[1], lineno))
TypeError: assertIn() takes exactly 3 arguments (4 given)


----------------------------------------------------------------------
Ran 47 tests in 0.119s

FAILED (errors=6, skipped=3)
```

**Comment by Arfrever** [comment]
Apparently problem is due to older version of testtools.
I suggest to specify minimal required version of testtools in `test-requirements.txt`.

**Comment by Arfrever** [comment]
Tests pass with testtools 1.0.0 and fail with testtools 0.9.39.

**Comment by berkerpeksag** [comment]
Thanks for report, but since 0.9.39 is an old release I don't think it's worth to update test-requirements.txt.
