### ISSUE TITLE
pip fails to install under Python 3.2

### ISSUE THREAD

**Issue by berkerpeksag** [testing-cabal/traceback2#12]
From https://travis-ci.org/testing-cabal/traceback2/jobs/298642765:

```
$ pip install -U pip wheel setuptools
$ pip install -r requirements.txt
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2.6/bin/pip", line 7, in <module>
    from pip import main
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pip/_vendor/requests/__init__.py", line 66, in <module>
    from .models import Request, Response, PreparedRequest
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/pip/_vendor/requests/models.py", line 856
    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
                                                      ^
SyntaxError: invalid syntax
```

We should probably stop invoking `pip install -U pip wheel setuptools` under Python 3.2.

**Comment by jelmer** [comment]
Closing this as python 3.2 is no longer supported.
